# Project ki unique pehchaan (SonarQube dashboard mein isi naam se dikhega)
sonar.projectKey=travelmemory
sonar.projectName=TravelMemory

# Konsa code scan karna hai (dono tiers)
sonar.sources=backend,frontend/src

# Kya scan NAHI karna (bekaar/generated files) jenkinsfile me
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js

sonar.sourceEncoding=UTF-8 